### ISSUE TITLE
Chromosomal Location for DASHit Guides

### ISSUE THREAD

**Issue by gianatcirolia** [czbiohub/special_ops_crispr_tools#4]
Hi,

For tiled guide design, it is valuable to know the location of the guides as well as the sequence of the guides at particular locations so that once guides are generated the experimenter can pick subsets of guides that hit specific locations if needed. 

Would it be possible to have the output CSV also contain the chromosomal location that matches to each selected guide?

Thank you so much for the help.

**Comment by EmperorDali** [comment]
This is implemented in ##46c0650819397a828886ca0607d4e78b1eefeea7
